version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  Coverage:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install .[tests]
            make test
            coverage xml
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t ${CODECOV_TOKEN}
      - store_artifacts:
          path: ~/log.txt

  Docs:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install .[docs]
            cd docs
            make html
      - store_artifacts:
          path: docs/_build/html
          destination: docs
      - store_artifacts:
          path: ~/log.txt
      - persist_to_workspace:
          root: docs/_build/html
          paths: .
      - attach_workspace:
          at: docs/_build/html
      - run: ls -ltrh docs/_build/html

# Invoke jobs via workflows
workflows:
  Coverage: 
    jobs:
      - Coverage
  Docs: 
    jobs:
      - Docs
