version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  setup-env:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            chmod +x miniconda.sh && ./miniconda.sh -b -p ~/miniconda
            export PATH="~/miniconda/bin:$PATH"
            source ~/miniconda/etc/profile.d/conda.sh
            conda create -n testenv --yes --quiet python=3
            conda activate testenv
          
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install .
            pip install codecov pytest-cov
            python -c "import research"
            make test
            coverage xml
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t ${CODECOV_TOKEN}
      - store_artifacts:
          path: ~/log.txt
  test-docs:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install .[dev]
            cd docs
            make html
      - store_artifacts:
          path: docs/_build/html
          destination: docs
      - store_artifacts:
          path: ~/log.txt
      - persist_to_workspace:
          root: docs/_build/html
          paths: .
      - attach_workspace:
          at: docs/_build/html
      - run: ls -ltrh docs/_build/html

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test: 
    jobs:
      - setup-env
      - build-and-test
  test-docs: 
    jobs:
      - setup-env
      - test-docs
